ALTER TYPE "WhatsAppMessageType" ADD VALUE IF NOT EXISTS 'NO_SHOW';
ALTER TYPE "WhatsAppMessageType" ADD VALUE IF NOT EXISTS 'CONFIRMATION_REPLY_CONFIRMED';
ALTER TYPE "WhatsAppMessageType" ADD VALUE IF NOT EXISTS 'CONFIRMATION_REPLY_RESCHEDULE';
