services:
  saudy-db:
    image: postgres:16-alpine
    container_name: saudy-db
    environment:
      - POSTGRES_USER=saudy_user
      - POSTGRES_PASSWORD=saudy_password
      - POSTGRES_DB=saudy_db
    ports:
      - '5432:5432'
    volumes:
      - saudy_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saudy_user -d saudy_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  saudy_db:
