import { FastifyInstance } from 'fastify';
import preAttendanceRoutes from './routes/pre-attendances';
import appointmentRoutes from './routes/appointments';
import consultationRoutes from './routes/consultations';
import reportRoutes from './routes/reports';
import reportWorklistRoutes from './routes/report-worklist';
import reportTemplateRoutes from './routes/report-templates';
import reportPhraseRoutes from './routes/report-phrases';
import reportConfigRoutes from './routes/report-config';
import reportAddendumRoutes from './routes/report-addendums';
import reportAuditLogRoutes from './routes/report-audit-logs';
import documentRoutes from './routes/documents';
import teaProfilesRoutes from './routes/tea-profiles';
import teaPreReservationsRoutes from './routes/tea-pre-reservations';
import convenioAuthorizationRoutes from './routes/convenio-authorizations';
import teaEvolutionTemplateRoutes from './routes/tea-evolution-templates';
import whatsappConfigRoutes from './routes/whatsapp-config';
import whatsappMessagesRoutes from './routes/whatsapp-messages';
import whatsappJobsRoutes from './routes/whatsapp-jobs';
import publicCheckInRoutes from './routes/public-check-in';
import mwlRoutes from './routes/mwl';
import preSchedulingRoutes from './routes/pre-scheduling';
import spellCheckRoutes from './routes/spell-check';

export default async function careModule(app: FastifyInstance) {
  app.register(publicCheckInRoutes, { prefix: '/public-check-in' });
  app.register(mwlRoutes, { prefix: '/mwl' });
  app.register(preSchedulingRoutes, { prefix: '/pre-scheduling' });
  app.register(preAttendanceRoutes, { prefix: '/pre-attendances' });
  app.register(appointmentRoutes, { prefix: '/appointments' });
  app.register(consultationRoutes, { prefix: '/consultations' });
  app.register(reportRoutes, { prefix: '/reports' });
  app.register(reportWorklistRoutes, { prefix: '/report-worklist' });
  app.register(reportTemplateRoutes, { prefix: '/report-templates' });
  app.register(reportPhraseRoutes, { prefix: '/report-phrases' });
  app.register(reportConfigRoutes, { prefix: '/report-config' });
  app.register(reportAddendumRoutes, { prefix: '/report-addendums' });
  app.register(reportAuditLogRoutes, { prefix: '/report-audit-logs' });
  app.register(documentRoutes, { prefix: '/documents' });
  app.register(teaProfilesRoutes, { prefix: '/tea-profiles' });
  app.register(teaPreReservationsRoutes, { prefix: '/tea-pre-reservations' });
  app.register(teaEvolutionTemplateRoutes, { prefix: '/tea-evolution-templates' });
  app.register(convenioAuthorizationRoutes, { prefix: '/convenio-authorizations' });
  app.register(whatsappConfigRoutes, { prefix: '/' });
  app.register(whatsappJobsRoutes, { prefix: '/' });
  app.register(whatsappMessagesRoutes, { prefix: '/' });
  app.register(spellCheckRoutes, { prefix: '/spell-check' });
}
