export const openapiSchemas = {
  Lead: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string', nullable: true },
      companyName: { type: 'string', nullable: true },
      message: { type: 'string', nullable: true },
      source: { type: 'string', nullable: true },
      status: { type: 'string', enum: ['NEW', 'CONTACTED', 'QUALIFIED', 'LOST'] },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  LeadCreate: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      companyName: { type: 'string' },
      message: { type: 'string' },
      source: { type: 'string' },
    },
    required: ['name', 'email', 'phone', 'message'],
  },
  LeadStatusUpdate: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['NEW', 'CONTACTED', 'QUALIFIED', 'LOST'] },
    },
    required: ['status'],
  },
  Ticket: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      flow: { type: 'string' },
      module: { type: 'string' },
      type: { type: 'string', enum: ['BUG', 'ERROR', 'IMPROVEMENT'] },
      description: { type: 'string' },
      status: { type: 'string', enum: ['OPEN', 'TRIAGE', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'] },
      priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      createdByUserId: { type: 'string', nullable: true },
      createdByName: { type: 'string', nullable: true },
      createdByEmail: { type: 'string', nullable: true },
      branchId: { type: 'string', nullable: true },
      branchName: { type: 'string', nullable: true },
      resolutionConfirmationDeadlineAt: { type: 'string', format: 'date-time', nullable: true },
      resolutionConfirmedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  TicketCreate: {
    type: 'object',
    properties: {
      flow: { type: 'string' },
      module: { type: 'string' },
      type: { type: 'string', enum: ['BUG', 'ERROR', 'IMPROVEMENT'] },
      description: { type: 'string' },
    },
    required: ['flow', 'module', 'type', 'description'],
  },
  TicketStatusUpdate: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['OPEN', 'TRIAGE', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'] },
    },
    required: ['status'],
  },
  TicketPriorityUpdate: {
    type: 'object',
    properties: {
      priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
    },
    required: ['priority'],
  },
  InventoryItem: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      code: { type: 'string' },
      name: { type: 'string' },
      category: { type: 'string' },
      unit: { type: 'string' },
      quantity: { type: 'number' },
      minQuantity: { type: 'number' },
      maxQuantity: { type: 'number' },
      unitPrice: { type: 'number' },
      expiryDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      notes: { type: 'string' },
      isActive: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  InventoryItemCreate: {
    type: 'object',
    properties: {
      code: { type: 'string' },
      name: { type: 'string' },
      category: { type: 'string' },
      unit: { type: 'string' },
      quantity: { type: 'number' },
      minQuantity: { type: 'number' },
      maxQuantity: { type: 'number' },
      unitPrice: { type: 'number' },
      expiryDate: { type: 'string', format: 'date' },
      notes: { type: 'string' },
    },
    required: ['code', 'name', 'expiryDate'],
  },
  InventoryItemUpdate: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      category: { type: 'string' },
      unit: { type: 'string' },
      quantity: { type: 'number' },
      minQuantity: { type: 'number' },
      maxQuantity: { type: 'number' },
      unitPrice: { type: 'number' },
      expiryDate: { type: 'string', format: 'date' },
      notes: { type: 'string' },
    },
  },
  FinanceEntry: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { type: 'string' },
      category: { type: 'string' },
      description: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      total: { type: 'number' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      paymentMethod: { type: 'string' },
      relatedName: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },
  FinanceEntryCreate: {
    type: 'object',
    properties: {
      type: { type: 'string' },
      category: { type: 'string' },
      description: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      dueDate: { type: 'string', format: 'date' },
      paymentMethod: { type: 'string' },
      relatedName: { type: 'string' },
    },
    required: ['type', 'value'],
  },
  FinanceEntryUpdate: {
    type: 'object',
    properties: {
      category: { type: 'string' },
      description: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      paymentMethod: { type: 'string' },
      relatedName: { type: 'string' },
    },
  },
  Invoice: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      number: { type: 'string' },
      sourceAppointmentId: { type: 'string', nullable: true },
      sourceConsultationId: { type: 'string', nullable: true },
      patientName: { type: 'string' },
      beneficiaryCardNumber: { type: 'string', nullable: true },
      beneficiaryPlan: { type: 'string', nullable: true },
      beneficiaryCardExpiry: { type: 'string', nullable: true },
      beneficiaryStatus: { type: 'string', nullable: true },
      holderName: { type: 'string', nullable: true },
      holderDocument: { type: 'string', nullable: true },
      dependentName: { type: 'string', nullable: true },
      dependentRelationship: { type: 'string', nullable: true },
      guideType: { type: 'string', nullable: true },
      operatorGuideNumber: { type: 'string', nullable: true },
      authorizationPassword: { type: 'string', nullable: true },
      authorizationDate: { type: 'string', format: 'date', nullable: true },
      authorizationExpiryDate: { type: 'string', format: 'date', nullable: true },
      authorizedAttendanceType: { type: 'string', nullable: true },
      packageValue: { type: 'number', nullable: true },
      materialsValue: { type: 'number', nullable: true },
      feesValue: { type: 'number', nullable: true },
      dailyValue: { type: 'number', nullable: true },
      gasesValue: { type: 'number', nullable: true },
      opmeValue: { type: 'number', nullable: true },
      expectedDiscountValue: { type: 'number', nullable: true },
      expectedGlosaValue: { type: 'number', nullable: true },
      cidCode: { type: 'string', nullable: true },
      clinicalIndication: { type: 'string', nullable: true },
      requestingProfessionalName: { type: 'string', nullable: true },
      requestingProfessionalCpf: { type: 'string', nullable: true },
      requestingProfessionalCouncil: { type: 'string', nullable: true },
      requestingProfessionalCouncilUf: { type: 'string', nullable: true },
      requestingProfessionalCouncilNumber: { type: 'string', nullable: true },
      requestingProfessionalCbo: { type: 'string', nullable: true },
      executingProfessionalName: { type: 'string', nullable: true },
      executingProfessionalCpf: { type: 'string', nullable: true },
      executingProfessionalCouncil: { type: 'string', nullable: true },
      executingProfessionalCouncilUf: { type: 'string', nullable: true },
      executingProfessionalCouncilNumber: { type: 'string', nullable: true },
      executingProfessionalCbo: { type: 'string', nullable: true },
      issuedAt: { type: 'string', format: 'date-time' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      convention: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      total: { type: 'number' },
      paymentMethod: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },
  InvoiceCreate: {
    type: 'object',
    properties: {
      number: { type: 'string' },
      sourceAppointmentId: { type: 'string' },
      sourceConsultationId: { type: 'string' },
      patientName: { type: 'string' },
      beneficiaryCardNumber: { type: 'string' },
      beneficiaryPlan: { type: 'string' },
      beneficiaryCardExpiry: { type: 'string' },
      beneficiaryStatus: { type: 'string' },
      holderName: { type: 'string' },
      holderDocument: { type: 'string' },
      dependentName: { type: 'string' },
      dependentRelationship: { type: 'string' },
      guideType: { type: 'string' },
      operatorGuideNumber: { type: 'string' },
      authorizationPassword: { type: 'string' },
      authorizationDate: { type: 'string', format: 'date' },
      authorizationExpiryDate: { type: 'string', format: 'date' },
      authorizedAttendanceType: { type: 'string' },
      packageValue: { type: 'number' },
      materialsValue: { type: 'number' },
      feesValue: { type: 'number' },
      dailyValue: { type: 'number' },
      gasesValue: { type: 'number' },
      opmeValue: { type: 'number' },
      expectedDiscountValue: { type: 'number' },
      expectedGlosaValue: { type: 'number' },
      cidCode: { type: 'string' },
      clinicalIndication: { type: 'string' },
      requestingProfessionalName: { type: 'string' },
      requestingProfessionalCpf: { type: 'string' },
      requestingProfessionalCouncil: { type: 'string' },
      requestingProfessionalCouncilUf: { type: 'string' },
      requestingProfessionalCouncilNumber: { type: 'string' },
      requestingProfessionalCbo: { type: 'string' },
      executingProfessionalName: { type: 'string' },
      executingProfessionalCpf: { type: 'string' },
      executingProfessionalCouncil: { type: 'string' },
      executingProfessionalCouncilUf: { type: 'string' },
      executingProfessionalCouncilNumber: { type: 'string' },
      executingProfessionalCbo: { type: 'string' },
      issuedAt: { type: 'string', format: 'date-time' },
      dueDate: { type: 'string', format: 'date' },
      convention: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      paymentMethod: { type: 'string' },
    },
    required: ['value'],
  },
  InvoiceUpdate: {
    type: 'object',
    properties: {
      patientName: { type: 'string' },
      beneficiaryCardNumber: { type: 'string' },
      beneficiaryPlan: { type: 'string' },
      beneficiaryCardExpiry: { type: 'string' },
      beneficiaryStatus: { type: 'string' },
      holderName: { type: 'string' },
      holderDocument: { type: 'string' },
      dependentName: { type: 'string' },
      dependentRelationship: { type: 'string' },
      guideType: { type: 'string' },
      operatorGuideNumber: { type: 'string' },
      authorizationPassword: { type: 'string' },
      authorizationDate: { type: 'string', format: 'date' },
      authorizationExpiryDate: { type: 'string', format: 'date' },
      authorizedAttendanceType: { type: 'string' },
      packageValue: { type: 'number' },
      materialsValue: { type: 'number' },
      feesValue: { type: 'number' },
      dailyValue: { type: 'number' },
      gasesValue: { type: 'number' },
      opmeValue: { type: 'number' },
      expectedDiscountValue: { type: 'number' },
      expectedGlosaValue: { type: 'number' },
      cidCode: { type: 'string' },
      clinicalIndication: { type: 'string' },
      requestingProfessionalName: { type: 'string' },
      requestingProfessionalCpf: { type: 'string' },
      requestingProfessionalCouncil: { type: 'string' },
      requestingProfessionalCouncilUf: { type: 'string' },
      requestingProfessionalCouncilNumber: { type: 'string' },
      requestingProfessionalCbo: { type: 'string' },
      executingProfessionalName: { type: 'string' },
      executingProfessionalCpf: { type: 'string' },
      executingProfessionalCouncil: { type: 'string' },
      executingProfessionalCouncilUf: { type: 'string' },
      executingProfessionalCouncilNumber: { type: 'string' },
      executingProfessionalCbo: { type: 'string' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      convention: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      paymentMethod: { type: 'string' },
    },
  },
  TissBatch: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      batchNumber: { type: 'string' },
      competenceMonth: { type: 'string' },
      convention: { type: 'string' },
      status: { type: 'string', enum: ['DRAFT', 'GENERATED', 'SENT', 'ACCEPTED', 'REJECTED', 'CLOSED'] },
      protocolNumber: { type: 'string', nullable: true },
      generatedXmlAt: { type: 'string', format: 'date-time', nullable: true },
      sentAt: { type: 'string', format: 'date-time', nullable: true },
      createdByUserId: { type: 'string', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
      items: {
        type: 'array',
        items: { $ref: 'TissBatchItem#' },
      },
      invoicesCount: { type: 'number' },
      totalValue: { type: 'number' },
    },
  },
  TissBatchItem: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      batchId: { type: 'string' },
      invoiceId: { type: 'string' },
      guideNumber: { type: 'string' },
      status: { type: 'string' },
      returnStatus: { type: 'string', nullable: true },
      returnCode: { type: 'string', nullable: true },
      returnMessage: { type: 'string', nullable: true },
      glosaValue: { type: 'number', nullable: true },
      isRepresented: { type: 'boolean' },
      representedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
      invoice: { $ref: 'Invoice#' },
    },
  },
  TissBatchCreate: {
    type: 'object',
    properties: {
      competenceMonth: { type: 'string' },
      convention: { type: 'string' },
      invoiceIds: {
        type: 'array',
        items: { type: 'string' },
        minItems: 1,
      },
    },
    required: ['competenceMonth', 'convention', 'invoiceIds'],
  },
  TissBatchStatusUpdate: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['DRAFT', 'GENERATED', 'SENT', 'ACCEPTED', 'REJECTED', 'CLOSED'] },
      protocolNumber: { type: 'string' },
    },
    required: ['status'],
  },
  TissBatchProtocolUpdate: {
    type: 'object',
    properties: {
      protocolNumber: { type: 'string' },
    },
    required: ['protocolNumber'],
  },
  TissBatchReturnCreate: {
    type: 'object',
    properties: {
      items: {
        type: 'array',
        minItems: 1,
        items: {
          type: 'object',
          properties: {
            itemId: { type: 'string' },
            guideNumber: { type: 'string' },
            status: { type: 'string', enum: ['ACCEPTED', 'PARTIAL', 'REJECTED'] },
            returnCode: { type: 'string' },
            returnMessage: { type: 'string' },
            glosaValue: { type: 'number' },
          },
          required: ['status'],
        },
      },
    },
    required: ['items'],
  },
  TissBatchReprocessCreate: {
    type: 'object',
    properties: {
      itemIds: {
        type: 'array',
        items: { type: 'string' },
      },
      competenceMonth: { type: 'string' },
    },
  },
  Delivery: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      patientName: { type: 'string' },
      documentType: { type: 'string' },
      availableAt: { type: 'string', format: 'date-time' },
      description: { type: 'string' },
      responsible: { type: 'string' },
      status: { type: 'string' },
      deliveredTo: { type: 'string' },
      deliveredAt: { type: 'string', format: 'date-time' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },
  DeliveryCreate: {
    type: 'object',
    properties: {
      patientName: { type: 'string' },
      documentType: { type: 'string' },
      availableAt: { type: 'string', format: 'date-time' },
      description: { type: 'string' },
      responsible: { type: 'string' },
      status: { type: 'string' },
      deliveredTo: { type: 'string' },
      deliveredAt: { type: 'string', format: 'date-time' },
    },
    required: ['patientName', 'documentType'],
  },
  DeliveryUpdate: {
    type: 'object',
    properties: {
      patientName: { type: 'string' },
      documentType: { type: 'string' },
      availableAt: { type: 'string', format: 'date-time' },
      description: { type: 'string' },
      responsible: { type: 'string' },
      status: { type: 'string' },
      deliveredTo: { type: 'string' },
      deliveredAt: { type: 'string', format: 'date-time' },
    },
  },
};
