export const openapiSchemas = {
  Lead: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string', nullable: true },
      companyName: { type: 'string', nullable: true },
      message: { type: 'string', nullable: true },
      source: { type: 'string', nullable: true },
      status: { type: 'string', enum: ['NEW', 'CONTACTED', 'QUALIFIED', 'LOST'] },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  LeadCreate: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      companyName: { type: 'string' },
      message: { type: 'string' },
      source: { type: 'string' },
    },
    required: ['name', 'email', 'phone', 'message'],
  },
  LeadStatusUpdate: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['NEW', 'CONTACTED', 'QUALIFIED', 'LOST'] },
    },
    required: ['status'],
  },
  Ticket: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      flow: { type: 'string' },
      module: { type: 'string' },
      type: { type: 'string', enum: ['BUG', 'ERROR', 'IMPROVEMENT'] },
      description: { type: 'string' },
      status: { type: 'string', enum: ['OPEN', 'TRIAGE', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'] },
      priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      createdByUserId: { type: 'string', nullable: true },
      createdByName: { type: 'string', nullable: true },
      createdByEmail: { type: 'string', nullable: true },
      branchId: { type: 'string', nullable: true },
      branchName: { type: 'string', nullable: true },
      resolutionConfirmationDeadlineAt: { type: 'string', format: 'date-time', nullable: true },
      resolutionConfirmedAt: { type: 'string', format: 'date-time', nullable: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  TicketCreate: {
    type: 'object',
    properties: {
      flow: { type: 'string' },
      module: { type: 'string' },
      type: { type: 'string', enum: ['BUG', 'ERROR', 'IMPROVEMENT'] },
      description: { type: 'string' },
    },
    required: ['flow', 'module', 'type', 'description'],
  },
  TicketStatusUpdate: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['OPEN', 'TRIAGE', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'] },
    },
    required: ['status'],
  },
  TicketPriorityUpdate: {
    type: 'object',
    properties: {
      priority: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
    },
    required: ['priority'],
  },
  InventoryItem: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      code: { type: 'string' },
      name: { type: 'string' },
      category: { type: 'string' },
      unit: { type: 'string' },
      quantity: { type: 'number' },
      minQuantity: { type: 'number' },
      maxQuantity: { type: 'number' },
      unitPrice: { type: 'number' },
      expiryDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      notes: { type: 'string' },
      isActive: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
  },
  InventoryItemCreate: {
    type: 'object',
    properties: {
      code: { type: 'string' },
      name: { type: 'string' },
      category: { type: 'string' },
      unit: { type: 'string' },
      quantity: { type: 'number' },
      minQuantity: { type: 'number' },
      maxQuantity: { type: 'number' },
      unitPrice: { type: 'number' },
      expiryDate: { type: 'string', format: 'date' },
      notes: { type: 'string' },
    },
    required: ['code', 'name', 'expiryDate'],
  },
  InventoryItemUpdate: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      category: { type: 'string' },
      unit: { type: 'string' },
      quantity: { type: 'number' },
      minQuantity: { type: 'number' },
      maxQuantity: { type: 'number' },
      unitPrice: { type: 'number' },
      expiryDate: { type: 'string', format: 'date' },
      notes: { type: 'string' },
    },
  },
  FinanceEntry: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      type: { type: 'string' },
      category: { type: 'string' },
      description: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      total: { type: 'number' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      paymentMethod: { type: 'string' },
      relatedName: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },
  FinanceEntryCreate: {
    type: 'object',
    properties: {
      type: { type: 'string' },
      category: { type: 'string' },
      description: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      dueDate: { type: 'string', format: 'date' },
      paymentMethod: { type: 'string' },
      relatedName: { type: 'string' },
    },
    required: ['type', 'value'],
  },
  FinanceEntryUpdate: {
    type: 'object',
    properties: {
      category: { type: 'string' },
      description: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      paymentMethod: { type: 'string' },
      relatedName: { type: 'string' },
    },
  },
  Invoice: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      number: { type: 'string' },
      patientName: { type: 'string' },
      issuedAt: { type: 'string', format: 'date-time' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      convention: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      total: { type: 'number' },
      paymentMethod: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },
  InvoiceCreate: {
    type: 'object',
    properties: {
      number: { type: 'string' },
      patientName: { type: 'string' },
      issuedAt: { type: 'string', format: 'date-time' },
      dueDate: { type: 'string', format: 'date' },
      convention: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      paymentMethod: { type: 'string' },
    },
    required: ['value'],
  },
  InvoiceUpdate: {
    type: 'object',
    properties: {
      patientName: { type: 'string' },
      dueDate: { type: 'string', format: 'date' },
      status: { type: 'string' },
      convention: { type: 'string' },
      value: { type: 'number' },
      discount: { type: 'number' },
      paymentMethod: { type: 'string' },
    },
  },
  Delivery: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      patientName: { type: 'string' },
      documentType: { type: 'string' },
      availableAt: { type: 'string', format: 'date-time' },
      description: { type: 'string' },
      responsible: { type: 'string' },
      status: { type: 'string' },
      deliveredTo: { type: 'string' },
      deliveredAt: { type: 'string', format: 'date-time' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
      isActive: { type: 'boolean' },
    },
  },
  DeliveryCreate: {
    type: 'object',
    properties: {
      patientName: { type: 'string' },
      documentType: { type: 'string' },
      availableAt: { type: 'string', format: 'date-time' },
      description: { type: 'string' },
      responsible: { type: 'string' },
      status: { type: 'string' },
      deliveredTo: { type: 'string' },
      deliveredAt: { type: 'string', format: 'date-time' },
    },
    required: ['patientName', 'documentType'],
  },
  DeliveryUpdate: {
    type: 'object',
    properties: {
      patientName: { type: 'string' },
      documentType: { type: 'string' },
      availableAt: { type: 'string', format: 'date-time' },
      description: { type: 'string' },
      responsible: { type: 'string' },
      status: { type: 'string' },
      deliveredTo: { type: 'string' },
      deliveredAt: { type: 'string', format: 'date-time' },
    },
  },
};
