import { FastifyInstance } from 'fastify';

// OpenAPI components for medical clinic system
export const swaggerComponents = {
  schemas: {
    // Doctor schemas
    Doctor: {
      type: 'object',
      additionalProperties: true,
      properties: {
        id: { type: 'string' },
        branchId: { type: 'string', nullable: true },
        crmType: { type: 'string' },
        crm: { type: 'string' },
        crmState: { type: 'string' },
        name: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        cellphone: { type: 'string', nullable: true },
        birthDate: { type: 'string', format: 'date-time' },
        gender: { type: 'string', enum: ['MALE', 'FEMALE', 'OTHER'] },
        cpf: { type: 'string' },
        rg: { type: 'string', nullable: true },
        specialty: { type: 'string' },
        specialties: { type: 'array', items: { type: 'string' } },
        consultationFee: { type: 'number', nullable: true },
        biography: { type: 'string', nullable: true },
        signatureImageBase64: { type: 'string', nullable: true },
        address: { type: 'string', nullable: true },
        addressNumber: { type: 'string', nullable: true },
        addressComplement: { type: 'string', nullable: true },
        neighborhood: { type: 'string', nullable: true },
        city: { type: 'string', nullable: true },
        state: { type: 'string', nullable: true },
        zipCode: { type: 'string', nullable: true },
        roomId: { type: 'string', nullable: true },
        roomIds: { type: 'array', items: { type: 'string' } },
        rooms: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              roomId: { type: 'string' },
              room: {
                type: 'object',
                nullable: true,
                properties: {
                  id: { type: 'string' },
                  name: { type: 'string' },
                  branchId: { type: 'string' },
                },
              },
            },
          },
        },
        isActive: { type: 'boolean' },
        workingDays: { type: 'array', items: { type: 'string' } },
        workingHoursStart: { type: 'string', nullable: true },
        workingHoursEnd: { type: 'string', nullable: true },
        especialidadeGroups: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              modalidadeId: { type: 'string', nullable: true },
              especialidadeId: { type: 'string', nullable: true },
              metodos: { type: 'array', items: { type: 'string' } },
              procedimentoIds: { type: 'array', items: { type: 'string' } },
            },
          },
        },
        branchIds: { type: 'array', items: { type: 'string' } },
        appointmentDurations: { type: 'array', items: { type: 'number' } },
        workingSchedules: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              days: { type: 'array', items: { type: 'string' } },
              hoursStart: { type: 'string' },
              hoursEnd: { type: 'string' },
            },
            required: ['days', 'hoursStart', 'hoursEnd'],
          },
        },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      example: {
        id: '9a2f4e6b-3b6a-4f1a-b0d6-123456789abc',
        crm: '123456',
        crmState: 'SP',
        name: 'Dr. João Silva',
        email: 'joao.silva@clinica.com',
        phone: '11999998888',
        cellphone: '11988887777',
        birthDate: '1980-05-15T00:00:00Z',
        gender: 'MALE',
        cpf: '12345678900',
        specialty: 'Cardiologia',
        specialties: ['Cardiologia', 'Clínica Médica'],
        consultationFee: 350.00,
        isActive: true,
        workingDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
        workingHoursStart: '08:00',
        workingHoursEnd: '18:00',
        workingSchedules: [
          { days: ['MONDAY', 'WEDNESDAY'], hoursStart: '08:00', hoursEnd: '12:00' },
          { days: ['THURSDAY', 'FRIDAY'], hoursStart: '14:00', hoursEnd: '18:00' },
        ],
        createdAt: '2026-01-30T12:00:00Z',
        updatedAt: '2026-01-30T12:00:00Z',
      },
    },
    DoctorCreate: {
      type: 'object',
      properties: {
        crm: { type: 'string' },
        crmState: { type: 'string' },
        name: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        cellphone: { type: 'string' },
        birthDate: { type: 'string', format: 'date' },
        gender: { type: 'string', enum: ['MALE', 'FEMALE', 'OTHER'] },
        cpf: { type: 'string' },
        rg: { type: 'string' },
        specialty: { type: 'string' },
        specialties: { type: 'array', items: { type: 'string' } },
        consultationFee: { type: 'number' },
        biography: { type: 'string' },
        signatureImageBase64: { type: 'string' },
        address: { type: 'string' },
        addressNumber: { type: 'string' },
        addressComplement: { type: 'string' },
        neighborhood: { type: 'string' },
        city: { type: 'string' },
        state: { type: 'string' },
        zipCode: { type: 'string' },
        roomId: { type: 'string' },
        roomIds: { type: 'array', items: { type: 'string' } },
        workingDays: { type: 'array', items: { type: 'string' } },
        workingHoursStart: { type: 'string' },
        workingHoursEnd: { type: 'string' },
        workingSchedules: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              days: { type: 'array', items: { type: 'string' } },
              hoursStart: { type: 'string' },
              hoursEnd: { type: 'string' },
            },
            required: ['days', 'hoursStart', 'hoursEnd'],
          },
        },
      },
      required: ['crm', 'crmState', 'name', 'email', 'cellphone', 'birthDate', 'gender', 'cpf', 'specialty'],
      example: {
        crm: '123456',
        crmState: 'SP',
        name: 'Dr. João Silva',
        email: 'joao.silva@clinica.com',
        phone: '11999998888',
        birthDate: '1980-05-15',
        gender: 'MALE',
        cpf: '12345678900',
        specialty: 'Cardiologia',
        specialties: ['Cardiologia', 'Clínica Médica'],
        consultationFee: 350.00,
        workingDays: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
        workingHoursStart: '08:00',
        workingHoursEnd: '18:00',
        workingSchedules: [
          { days: ['MONDAY', 'WEDNESDAY'], hoursStart: '08:00', hoursEnd: '12:00' },
          { days: ['THURSDAY', 'FRIDAY'], hoursStart: '14:00', hoursEnd: '18:00' },
        ],
      },
    },
    DoctorUpdate: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        cellphone: { type: 'string' },
        specialty: { type: 'string' },
        specialties: { type: 'array', items: { type: 'string' } },
        consultationFee: { type: 'number' },
        biography: { type: 'string' },
        signatureImageBase64: { type: 'string' },
        address: { type: 'string' },
        addressNumber: { type: 'string' },
        addressComplement: { type: 'string' },
        neighborhood: { type: 'string' },
        city: { type: 'string' },
        state: { type: 'string' },
        zipCode: { type: 'string' },
        roomId: { type: 'string', nullable: true },
        roomIds: { type: 'array', items: { type: 'string' } },
        isActive: { type: 'boolean' },
        workingDays: { type: 'array', items: { type: 'string' } },
        workingHoursStart: { type: 'string' },
        workingHoursEnd: { type: 'string' },
        workingSchedules: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              days: { type: 'array', items: { type: 'string' } },
              hoursStart: { type: 'string' },
              hoursEnd: { type: 'string' },
            },
            required: ['days', 'hoursStart', 'hoursEnd'],
          },
        },
      },
      example: {
        specialty: 'Cardiologia Intervencionista',
        consultationFee: 400.00,
        workingDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
        workingSchedules: [
          { days: ['MONDAY', 'WEDNESDAY'], hoursStart: '08:00', hoursEnd: '12:00' },
          { days: ['THURSDAY', 'FRIDAY'], hoursStart: '14:00', hoursEnd: '18:00' },
        ],
      },
    },

    // Patient schemas
    Patient: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        email: { type: 'string', nullable: true },
        phone: { type: 'string', nullable: true },
        cellphone: { type: 'string' },
        birthDate: { type: 'string', format: 'date-time' },
        gender: { type: 'string', enum: ['MALE', 'FEMALE', 'OTHER'] },
        cpf: { type: 'string' },
        rg: { type: 'string', nullable: true },
        maritalStatus: { type: 'string', enum: ['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'], nullable: true },
        occupation: { type: 'string', nullable: true },
        address: { type: 'string', nullable: true },
        addressNumber: { type: 'string', nullable: true },
        addressComplement: { type: 'string', nullable: true },
        neighborhood: { type: 'string', nullable: true },
        city: { type: 'string', nullable: true },
        state: { type: 'string', nullable: true },
        zipCode: { type: 'string', nullable: true },
        emergencyContactName: { type: 'string', nullable: true },
        emergencyContactPhone: { type: 'string', nullable: true },
        emergencyContactRelationship: { type: 'string', nullable: true },
        hasGuardian: { type: 'boolean' },
        guardianName: { type: 'string', nullable: true },
        guardianCpf: { type: 'string', nullable: true },
        guardianPhone: { type: 'string', nullable: true },
        guardianRelationship: { type: 'string', nullable: true },
        hasHealthInsurance: { type: 'boolean' },
        healthInsuranceName: { type: 'string', nullable: true },
        healthInsuranceNumber: { type: 'string', nullable: true },
        healthInsuranceExpiry: { type: 'string', format: 'date-time', nullable: true },
        bloodType: { type: 'string', enum: ['A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE'], nullable: true },
        allergies: { type: 'array', items: { type: 'string' } },
        chronicConditions: { type: 'array', items: { type: 'string' } },
        currentMedications: { type: 'array', items: { type: 'string' } },
        observations: { type: 'string', nullable: true },
        isActive: { type: 'boolean' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
      example: {
        id: '9a2f4e6b-3b6a-4f1a-b0d6-123456789abc',
        name: 'Maria Santos',
        email: 'maria.santos@email.com',
        cellphone: '11988887777',
        birthDate: '1990-03-20T00:00:00Z',
        gender: 'FEMALE',
        cpf: '98765432100',
        hasHealthInsurance: true,
        healthInsuranceName: 'Unimed',
        bloodType: 'O_POSITIVE',
        allergies: ['Dipirona', 'Penicilina'],
        chronicConditions: ['Hipertensão'],
        currentMedications: ['Losartana 50mg'],
        isActive: true,
        createdAt: '2026-01-30T12:00:00Z',
        updatedAt: '2026-01-30T12:00:00Z',
      },
    },
    PatientCreate: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        cellphone: { type: 'string' },
        birthDate: { type: 'string', format: 'date' },
        gender: { type: 'string', enum: ['MALE', 'FEMALE', 'OTHER'] },
        cpf: { type: 'string' },
        rg: { type: 'string' },
        maritalStatus: { type: 'string', enum: ['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'] },
        occupation: { type: 'string' },
        address: { type: 'string' },
        addressNumber: { type: 'string' },
        addressComplement: { type: 'string' },
        neighborhood: { type: 'string' },
        city: { type: 'string' },
        state: { type: 'string' },
        zipCode: { type: 'string' },
        emergencyContactName: { type: 'string' },
        emergencyContactPhone: { type: 'string' },
        emergencyContactRelationship: { type: 'string' },
        hasGuardian: { type: 'boolean' },
        guardianName: { type: 'string' },
        guardianCpf: { type: 'string' },
        guardianPhone: { type: 'string' },
        guardianRelationship: { type: 'string' },
        hasHealthInsurance: { type: 'boolean' },
        healthInsuranceName: { type: 'string' },
        healthInsuranceNumber: { type: 'string' },
        healthInsuranceExpiry: { type: 'string', format: 'date' },
        bloodType: { type: 'string', enum: ['A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE'] },
        allergies: { type: 'array', items: { type: 'string' } },
        chronicConditions: { type: 'array', items: { type: 'string' } },
        currentMedications: { type: 'array', items: { type: 'string' } },
        observations: { type: 'string' },
      },
      required: ['name', 'cellphone', 'birthDate', 'gender', 'cpf'],
      example: {
        name: 'Maria Santos',
        email: 'maria.santos@email.com',
        cellphone: '11988887777',
        birthDate: '1990-03-20',
        gender: 'FEMALE',
        cpf: '98765432100',
        hasHealthInsurance: true,
        healthInsuranceName: 'Unimed',
        healthInsuranceNumber: '123456789',
        bloodType: 'O_POSITIVE',
        allergies: ['Dipirona', 'Penicilina'],
        chronicConditions: ['Hipertensão'],
      },
    },
    PatientUpdate: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        email: { type: 'string' },
        phone: { type: 'string' },
        cellphone: { type: 'string' },
        maritalStatus: { type: 'string', enum: ['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER'] },
        occupation: { type: 'string' },
        address: { type: 'string' },
        addressNumber: { type: 'string' },
        addressComplement: { type: 'string' },
        neighborhood: { type: 'string' },
        city: { type: 'string' },
        state: { type: 'string' },
        zipCode: { type: 'string' },
        emergencyContactName: { type: 'string' },
        emergencyContactPhone: { type: 'string' },
        emergencyContactRelationship: { type: 'string' },
        hasGuardian: { type: 'boolean' },
        guardianName: { type: 'string' },
        guardianCpf: { type: 'string' },
        guardianPhone: { type: 'string' },
        guardianRelationship: { type: 'string' },
        hasHealthInsurance: { type: 'boolean' },
        healthInsuranceName: { type: 'string' },
        healthInsuranceNumber: { type: 'string' },
        healthInsuranceExpiry: { type: 'string', format: 'date' },
        bloodType: { type: 'string', enum: ['A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE'] },
        allergies: { type: 'array', items: { type: 'string' } },
        chronicConditions: { type: 'array', items: { type: 'string' } },
        currentMedications: { type: 'array', items: { type: 'string' } },
        observations: { type: 'string' },
        isActive: { type: 'boolean' },
      },
      example: {
        hasHealthInsurance: true,
        healthInsuranceName: 'Bradesco Saúde',
        healthInsuranceNumber: '987654321',
        allergies: ['Dipirona', 'Penicilina', 'AAS'],
      },
    },

    // Medical Record schemas
    MedicalRecord: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        patientId: { type: 'string' },
        consultationId: { type: 'string', nullable: true },
        doctorId: { type: 'string', nullable: true },
        riskClassification: { type: 'string', nullable: true },
        chiefComplaint: { type: 'string', nullable: true },
        historyOfPresentIllness: { type: 'string', nullable: true },
        physicalExamination: { type: 'string', nullable: true },
        diagnosis: { type: 'string', nullable: true },
        treatment: { type: 'string', nullable: true },
        prescriptions: { type: 'string', nullable: true },
        examRequests: { type: 'string', nullable: true },
        notes: { type: 'string', nullable: true },
        bloodPressureSystolic: { type: 'number', nullable: true },
        bloodPressureDiastolic: { type: 'number', nullable: true },
        heartRate: { type: 'number', nullable: true },
        respiratoryRate: { type: 'number', nullable: true },
        temperature: { type: 'number', nullable: true },
        oxygenSaturation: { type: 'number', nullable: true },
        weight: { type: 'number', nullable: true },
        height: { type: 'number', nullable: true },
        bmi: { type: 'number', nullable: true },
        recordDate: { type: 'string', format: 'date-time' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        patient: { $ref: 'Patient#' },
        doctor: { $ref: 'Doctor#' },
      },
      example: {
        id: '9a2f4e6b-3b6a-4f1a-b0d6-123456789abc',
        patientId: '8b3f5e7c-4c7b-5f2b-c1e7-234567890def',
        doctorId: '7c4f6e8d-5d8c-6f3c-d2f8-345678901ghi',
        chiefComplaint: 'Dor de cabeça persistente há 3 dias',
        diagnosis: 'Cefaleia tensional',
        treatment: 'Repouso e analgésicos',
        prescriptions: 'Paracetamol 750mg - 1 comprimido a cada 6 horas se dor',
        bloodPressureSystolic: 120,
        bloodPressureDiastolic: 80,
        heartRate: 72,
        temperature: 36.5,
        weight: 70.5,
        height: 1.75,
        bmi: 23.02,
        recordDate: '2026-01-30T14:30:00Z',
        createdAt: '2026-01-30T14:30:00Z',
        updatedAt: '2026-01-30T14:30:00Z',
      },
    },
    MedicalRecordCreate: {
      type: 'object',
      properties: {
        patientId: { type: 'string' },
        consultationId: { type: 'string' },
        doctorId: { type: 'string' },
        riskClassification: { type: 'string' },
        chiefComplaint: { type: 'string' },
        historyOfPresentIllness: { type: 'string' },
        physicalExamination: { type: 'string' },
        diagnosis: { type: 'string' },
        treatment: { type: 'string' },
        prescriptions: { type: 'string' },
        examRequests: { type: 'string' },
        notes: { type: 'string' },
        bloodPressureSystolic: { type: 'number' },
        bloodPressureDiastolic: { type: 'number' },
        heartRate: { type: 'number' },
        respiratoryRate: { type: 'number' },
        temperature: { type: 'number' },
        oxygenSaturation: { type: 'number' },
        weight: { type: 'number' },
        height: { type: 'number' },
        recordDate: { type: 'string', format: 'date-time' },
      },
      required: ['patientId'],
      example: {
        patientId: '8b3f5e7c-4c7b-5f2b-c1e7-234567890def',
        doctorId: '7c4f6e8d-5d8c-6f3c-d2f8-345678901ghi',
        chiefComplaint: 'Dor de cabeça persistente há 3 dias',
        diagnosis: 'Cefaleia tensional',
        treatment: 'Repouso e analgésicos',
        prescriptions: 'Paracetamol 750mg - 1 comprimido a cada 6 horas se dor',
        bloodPressureSystolic: 120,
        bloodPressureDiastolic: 80,
        heartRate: 72,
        temperature: 36.5,
        weight: 70.5,
        height: 1.75,
      },
    },
    MedicalRecordUpdate: {
      type: 'object',
      properties: {
        chiefComplaint: { type: 'string' },
        historyOfPresentIllness: { type: 'string' },
        riskClassification: { type: 'string' },
        physicalExamination: { type: 'string' },
        diagnosis: { type: 'string' },
        treatment: { type: 'string' },
        prescriptions: { type: 'string' },
        examRequests: { type: 'string' },
        notes: { type: 'string' },
        bloodPressureSystolic: { type: 'number' },
        bloodPressureDiastolic: { type: 'number' },
        heartRate: { type: 'number' },
        respiratoryRate: { type: 'number' },
        temperature: { type: 'number' },
        oxygenSaturation: { type: 'number' },
        weight: { type: 'number' },
        height: { type: 'number' },
      },
      example: {
        diagnosis: 'Cefaleia tensional com componente cervicogênico',
        treatment: 'Repouso, analgésicos e fisioterapia',
        notes: 'Paciente relatou melhora parcial',
      },
    },
  },
};

