ALTER TABLE "medical_equipments"
ADD COLUMN IF NOT EXISTS "integrationType" TEXT NOT NULL DEFAULT 'MWL_BRIDGE',
ADD COLUMN IF NOT EXISTS "bridgeIdentifier" TEXT,
ADD COLUMN IF NOT EXISTS "mwlRemoteAeTitle" TEXT,
ADD COLUMN IF NOT EXISTS "storeRemoteAeTitle" TEXT,
ADD COLUMN IF NOT EXISTS "mwlHost" TEXT,
ADD COLUMN IF NOT EXISTS "mwlPort" INTEGER,
ADD COLUMN IF NOT EXISTS "storeHost" TEXT,
ADD COLUMN IF NOT EXISTS "storePort" INTEGER,
ADD COLUMN IF NOT EXISTS "lastTestStatus" TEXT,
ADD COLUMN IF NOT EXISTS "lastTestMessage" TEXT,
ADD COLUMN IF NOT EXISTS "lastTestedAt" TIMESTAMP(3);

ALTER TABLE "medical_equipments"
DROP COLUMN IF EXISTS "remoteAeTitle",
DROP COLUMN IF EXISTS "dicomHost",
DROP COLUMN IF EXISTS "dicomPort";
